data_dir: ../dataset
model_dir: ../model
result_dir: ../result
data_name: ML1m
batch_size: 1000
test_size: 1000
selection_epoch: 1
weight_epoch: 0
selection_lr: 0.01
weight_lr: 0.001
num_candidate: 101
selection_rate: 0.5
deep_layer: [ 8 ]
policy_layer: [ 16 ]
num_layer: 2
topn: [ 10, 20 ]